---
- name: Sync instances
  ansible.builtin.command: "gamectl sync all"
  become: true

- name: Restart instances
  ansible.builtin.shell: |
    systemctl reset-failed 'ark@*' 2>/dev/null || true
    gamectl restart all
  changed_when: true
